// MongoDB initialization script
// Connects to MongoDB, creates each database listed in `databases`,
// creates the ApiEndpointConfigs collection if missing, and seeds it.
//
// Usage:
//   mongosh "mongodb://${MONGO_USER}:${MONGO_PASS}@localhost:27018/?authSource=admin" --file init-mongo.js

// ─── Configuration ───────────────────────────────────────────────────────────

const COLLECTION_NAME = "ApiEndpointConfigs";

// Add more database names here as needed.
// The collection + seed data will be created for every entry in this array.
const databases = [
  "Da465892d428b497e9bb1a631b7e91548"
];

// ─── Seed data (EJSON – dates are parsed automatically) ──────────────────────

const seedDataRaw = [
  {"_id":"87976953-9a6e-43c7-a677-28ddc719c35f","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Authentication","Method":"POST","Endpoint":"/Authentication/Logout","Description":"Logs out the current user session using the provided refresh token.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"8adac963-4434-4702-b4fa-deabac7b976e","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Authentication","Method":"POST","Endpoint":"/Authentication/LogoutAll","Description":"Logs out the current user from all active sessions.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"4297cebf-60c5-4dda-9aaa-e22cf7bc3482","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Authentication","Method":"POST","Endpoint":"/Authentication/SaveOIDCClient","Description":"Creates or updates an OIDC client credential for a project.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"fcc1dc17-3069-40cd-a034-a4e9dd62ebc0","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Authentication","Method":"GET","Endpoint":"/Authentication/GetOIDCClient","Description":"Retrieves a single OIDC client by project key and client ID.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"5d40668b-f516-48fa-9696-5d8349805fa9","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Authentication","Method":"GET","Endpoint":"/Authentication/GetOIDCClients","Description":"Retrieves all OIDC clients for a given project key.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"b4f0d14c-a9b3-407e-8377-cc4a2464aa86","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Authentication","Method":"POST","Endpoint":"/Authentication/DeleteOIDCClient","Description":"Deletes an OIDC client by item ID and project key.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"eb528f3b-145d-4881-94ad-156ad43204c1","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Authentication","Method":"POST","Endpoint":"/Authentication/GenerateUserCode","Description":"Generates a time-limited user code linked to a client ID.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"bc64b0fd-4a8d-48da-8f30-f5510806b970","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Authentication","Method":"GET","Endpoint":"/Authentication/GetUserCodes","Description":"Retrieves all user codes associated with the current user.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"7ca72fd3-8231-413a-b606-245e1347e82d","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Authentication","Method":"POST","Endpoint":"/Authentication/SaveClientCredential","Description":"Creates a new client credential with roles for a project.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"cbe5ddc6-7fa9-4794-bc62-a41cc203ced1","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Authentication","Method":"POST","Endpoint":"/Authentication/DeleteClientCredential","Description":"Deletes a client credential by item ID and project key.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"72908d8e-f397-430e-b793-2ebb782599b7","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Authentication","Method":"GET","Endpoint":"/Authentication/GetClientCredentials","Description":"Retrieves all client credentials for a given project key.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"a077b074-492d-41c8-9dc9-643f78d1641b","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Authentication","Method":"GET","Endpoint":"/Authentication/Authorize","Description":"Initiates an OAuth2 authorization code flow with response_type, client_id, state, redirect_uri, scope, and nonce.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"ed7309ec-7948-462d-a8b9-ab69bbde1e9e","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Authentication","Method":"POST","Endpoint":"/Authentication/Token","Description":"Issues tokens supporting multiple grant types: authorization_code, password, refresh_token, and device code, with optional MFA and biometric parameters.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":true,"MfaType":"Email, SMS, TOTP, Biometric"},
  {"_id":"7d478ff2-975a-455d-a1c5-2721b8bb5a7d","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Authentication","Method":"POST","Endpoint":"/Authentication/GetSocialLogInEndPoint","Description":"Returns the social login redirect URL for a specified provider and audience.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"1568d311-924d-4f99-b086-d2a03033b554","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Authentication","Method":"POST","Endpoint":"/Authentication/Login","Description":"Authenticates a user with username and password within an OIDC flow context.","IsCaptchaRequired":true,"CaptchaProvider":"","IsMfaRequired":true,"MfaType":"Email, SMS, TOTP"},
  {"_id":"79c74046-5265-4485-bdbf-f184b5647a05","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Authentication","Method":"GET","Endpoint":"/Authentication/GetUserInfo","Description":"Returns profile information for the currently authenticated user.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"ac6f6f2a-f44f-4f69-90e8-b4a9310acce8","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Authentication","Method":"POST","Endpoint":"/Authentication/UserAcknowledgement","Description":"Records user acknowledgement for an OIDC consent or acknowledgement screen.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"c84473c3-0271-47ff-94c1-be8bdc13747f","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Authentication","Method":"POST","Endpoint":"/Authentication/SaveSsoCredential","Description":"Creates or updates an SSO credential configuration for a project.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"13add127-6422-4a27-9c20-77bffde4c04e","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Authentication","Method":"POST","Endpoint":"/Authentication/DeleteSsoCredential","Description":"Deletes an SSO credential by item ID and project key.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"3c0fbea3-f013-4cea-a022-c4dab34c61bf","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Authentication","Method":"GET","Endpoint":"/Authentication/GetSsoCredential","Description":"Retrieves a single SSO credential by project key and item ID.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"64b449fb-5d3f-4d12-bc8d-ba090b97f71f","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Authentication","Method":"GET","Endpoint":"/Authentication/GetSsoCredentials","Description":"Retrieves all SSO credentials for a given project key.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"963e6058-36c0-4dca-ba45-fd7b20c9702b","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Authentication","Method":"POST","Endpoint":"/Authentication/UpdateStatus","Description":"Enables or disables an SSO credential by item ID.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"b0c22812-5a47-435c-be46-6ec59d9d87d8","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Authentication","Method":"GET","Endpoint":"/Authentication/GetLoginOptions","Description":"Retrieves available login options for the current context.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"9c78a8b2-d8b4-499e-8420-12e25f657498","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Captcha","Method":"POST","Endpoint":"/Captcha/Create","Description":"Creates a new captcha challenge for a given configuration name.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"e4eb3d77-f18c-4cd1-8363-3ec9e3520182","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Captcha","Method":"POST","Endpoint":"/Captcha/Submit","Description":"Submits a captcha answer by ID and value, returning a verification code on success.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"115cbdee-522e-4502-b46e-4c02696c6cfc","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Captcha","Method":"GET","Endpoint":"/Captcha/Verify","Description":"Verifies a captcha verification code against a configuration name.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"d7e8fd89-166d-4b89-a87d-c5104613a136","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Discovery","Method":"GET","Endpoint":"/.well-known/jwks.json","Description":"Returns the JSON Web Key Set (JWKS) for token signature verification.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"bbceff47-2d80-433c-86ba-97fd6e96d7aa","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Discovery","Method":"GET","Endpoint":"/.well-known/openid-configuration","Description":"Returns the OpenID Connect discovery document for a project.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"139bb317-d055-42a7-bd96-a1176e9e1e06","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"POST","Endpoint":"/Iam/Activate","Description":"Activates a user account using an activation code, with optional password and captcha.","IsCaptchaRequired":true,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"18610f65-4533-4dbc-9f55-922259f6e4a0","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"POST","Endpoint":"/Iam/Recover","Description":"Initiates account recovery by sending a reset link to the user email.","IsCaptchaRequired":true,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"383da845-c583-4965-b3b8-d45c4e32fec0","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"POST","Endpoint":"/Iam/ResetPassword","Description":"Resets the user password using a reset code, with optional captcha and logout-all option.","IsCaptchaRequired":true,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"99288499-7de2-444a-b024-1281a89e9d9f","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"POST","Endpoint":"/Iam/ChangePassword","Description":"Changes the authenticated user password by providing old and new passwords.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"8f30bbdd-085f-424e-9d6a-45e1a660567c","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"POST","Endpoint":"/Iam/ResendActivation","Description":"Resends the activation email to a user by user ID.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"105b9cc2-e52b-4c54-ae81-c8eb417e7cf1","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"POST","Endpoint":"/Iam/ValidateActivationCode","Description":"Validates an activation code without completing the activation.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"e4cdca2a-90f5-4861-a36b-be636b2d2c89","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"GET","Endpoint":"/Iam/GetSessions","Description":"Retrieves paginated active sessions for a project, filterable by user ID.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"45a2a64d-7a42-46fb-a5e4-5aece114df1d","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"GET","Endpoint":"/Iam/GetHistories","Description":"Retrieves paginated login/event histories for a project, filterable by user ID.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"9b7ea2a2-72d4-4b66-82e8-c3ec21a91e31","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"POST","Endpoint":"/Iam/CreatePermission","Description":"Creates a new permission with name, type, resource, severity and optional tags.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"729e3c28-59f1-4d03-95dd-c2455bc6618d","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"POST","Endpoint":"/Iam/UpdatePermission","Description":"Updates an existing permission by item ID.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"09442459-b86a-4c1a-8aa8-a0470f543bce","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"POST","Endpoint":"/Iam/CreateRole","Description":"Creates a new role with a name, slug, and description.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"856b4841-681e-48b7-9b53-16b6b2269204","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"POST","Endpoint":"/Iam/UpdateRole","Description":"Updates an existing role name and description by item ID.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"37d3be32-dd35-4497-bee0-542808da377a","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"POST","Endpoint":"/Iam/GetPermissions","Description":"Retrieves a paginated, filtered list of permissions for a project.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"315886a2-96f7-40ff-a75b-b1d60fadaa3c","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"GET","Endpoint":"/Iam/GetPermissionsGroupBySeverity","Description":"Returns permission counts grouped by severity level for a project.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"3c350029-1b61-49d5-a90f-f6eda0464dba","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"GET","Endpoint":"/Iam/GetPermission","Description":"Retrieves a single permission by ID and project key.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"ebf2f288-7b47-4c8b-82b3-9684fae6f62b","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"POST","Endpoint":"/Iam/GetRoles","Description":"Retrieves a paginated, filtered list of roles for a project.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"3c02d1f5-84ba-4925-b289-bad17fbe73d1","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"GET","Endpoint":"/Iam/GetRole","Description":"Retrieves a single role by project key and role ID.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"05106e9e-b310-4ebd-a8e3-ed96c3dc60a6","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"POST","Endpoint":"/Iam/SetRoles","Description":"Adds or removes permissions on a role identified by slug.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"2b9e4bc7-3d81-4547-8c97-6283daee3942","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"GET","Endpoint":"/Iam/GetResourceGroups","Description":"Returns all resource group names and their permission counts for a project.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"ccd46da1-e36a-43ec-8aa0-3f699e50afd3","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"POST","Endpoint":"/Iam/Create","Description":"Creates a new user with profile, credentials, MFA settings, and optional organization membership.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"db93efba-65a7-49be-8445-26b9eaab0759","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"POST","Endpoint":"/Iam/Update","Description":"Updates an existing user profile, MFA settings, roles, and permissions.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"93e69ad7-e71f-48c2-a8a8-7975dac659e3","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"POST","Endpoint":"/Iam/Deactivate","Description":"Deactivates a user account by user ID and project key.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"89c56c58-09cb-482a-9386-bf06f9998026","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"POST","Endpoint":"/Iam/UpdateAccount","Description":"Updates the currently authenticated user own account profile.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"23ff8f6f-60d8-428a-b910-ec99e3889afd","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"POST","Endpoint":"/Iam/GetUsers","Description":"Retrieves a paginated, filtered list of users for a project.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"3a5ddb25-d135-422c-ab18-002a753986c5","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"GET","Endpoint":"/Iam/GetUser","Description":"Retrieves a single user by ID and project key.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"64484737-37d0-4014-90ca-fe3ed27b2937","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"GET","Endpoint":"/Iam/GetUserRoles","Description":"Retrieves all roles assigned to a user by user ID and project key.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"ef24299f-e8cb-4e38-b1b1-041fee5490af","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"GET","Endpoint":"/Iam/GetUserPermissions","Description":"Retrieves all permissions assigned to a user by user ID and project key.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"e00bf416-545d-4dc5-ad1b-9a3cafbccc16","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"POST","Endpoint":"/Iam/GetAccounts","Description":"Retrieves a paginated, filtered list of accounts (self-registered users).","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"09c9b090-105b-4afc-8f8d-cac9144ec4da","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"GET","Endpoint":"/Iam/GetAccount","Description":"Retrieves the currently authenticated user account details including permissions.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"b6fda834-4f02-416a-8370-cd3356287f0a","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"GET","Endpoint":"/Iam/GetAccountRoles","Description":"Retrieves all roles for the currently authenticated account.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"009e07d7-ba32-44f5-9244-dabc9e840a34","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"GET","Endpoint":"/Iam/GetAccountPermissions","Description":"Retrieves all permissions for the currently authenticated account.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"e94dd4e8-196d-4387-ae4a-11658d0847cf","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"POST","Endpoint":"/Iam/SaveRolesAndPermissions","Description":"Assigns roles and permissions to a user via organization memberships.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"80797540-6836-4b90-9656-e7c32a633c7c","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"GET","Endpoint":"/Iam/IsEmailAvaiable","Description":"Checks whether an email address is available for registration in a project.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"e9a767b3-3005-433c-a39c-9087867e8255","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"GET","Endpoint":"/Iam/GetUserTimelines","Description":"Retrieves the event timeline history for a user with pagination and event filtering.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"0e6c2d7b-8d34-47fe-bb6c-f746a8fbd20f","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"POST","Endpoint":"/Iam/SaveOrganization","Description":"Creates or updates an organization by name and enable status.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"f038b57e-c611-4db6-8032-55969d3adf96","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"GET","Endpoint":"/Iam/GetOrganizations","Description":"Retrieves a paginated, filtered list of organizations for a project.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"bfc7c390-0368-4534-9903-f0410a01de4e","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"GET","Endpoint":"/Iam/GetOrganization","Description":"Retrieves a single organization by project key and item ID.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"737eb00b-4005-439e-9f08-ee6430a058ad","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"POST","Endpoint":"/Iam/SaveOrganizationConfig","Description":"Saves organization configuration including multi-org settings, creation flags, and default roles.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"b424bf23-8b22-4973-9e44-e55ad45595ee","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"GET","Endpoint":"/Iam/GetOrganizationConfig","Description":"Retrieves the organization configuration for a project key.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"802e3eb8-5c7a-460d-b003-72a85e2b7970","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"POST","Endpoint":"/Iam/SaveSignUpSetting","Description":"Saves sign-up settings controlling email/password and SSO registration for a project.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"0668eab1-2cd5-4bda-a56d-414138fd5282","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Iam","Method":"GET","Endpoint":"/Iam/GetSignUpSetting","Description":"Retrieves sign-up settings by item ID and project key.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"f70bb823-a4b0-4c32-b47f-90e60c9aaa2e","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Mfa","Method":"POST","Endpoint":"/Mfa/GenerateOTP","Description":"Generates and sends an OTP to a user via the specified MFA type.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"22554ea1-4a7b-4e64-80de-21e4d66e3793","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Mfa","Method":"POST","Endpoint":"/Mfa/VerifyOTP","Description":"Verifies an OTP code by MFA ID and authentication type.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"435a3364-f347-4c2c-94f9-656b2efcc86c","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Mfa","Method":"POST","Endpoint":"/Mfa/DisableUserMfa","Description":"Disables MFA for a user by user ID and project key.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"735ca290-2ec1-4f15-b6b0-3686565aba92","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Mfa","Method":"GET","Endpoint":"/Mfa/SetUpTotp","Description":"Returns a QR code and secret for setting up TOTP-based MFA for a user.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""},
  {"_id":"cd43f49d-494f-4cf1-8b24-51c05c3fa048","CreatedDate":{"$date":{"$numberLong":"-62135596800000"}},"LastUpdatedDate":{"$date":"2026-04-19T14:26:24.980Z"},"CreatedBy":null,"Language":null,"LastUpdatedBy":"","OrganizationIds":[],"Tags":[],"Service":"idp","Version":"v1","BaseUrl":"https://dev-api.seliseblocks.com","Controller":"Mfa","Method":"POST","Endpoint":"/Mfa/ResendOtp","Description":"Resends a previously generated OTP using the MFA session ID.","IsCaptchaRequired":false,"CaptchaProvider":"","IsMfaRequired":false,"MfaType":""}
];

// EJSON.deserialize converts Extended JSON date objects to native BSON Date values.
const seedData = seedDataRaw.map(doc => EJSON.deserialize(doc));

// ─── Initialization loop ──────────────────────────────────────────────────────

databases.forEach(dbName => {
  print(`\n=== Database: ${dbName} ===`);
  const targetDb = db.getSiblingDB(dbName);

  const existingCollections = targetDb.getCollectionNames();

  if (!existingCollections.includes(COLLECTION_NAME)) {
    print(`  Creating collection '${COLLECTION_NAME}'...`);
    targetDb.createCollection(COLLECTION_NAME);
  } else {
    print(`  Collection '${COLLECTION_NAME}' already exists.`);
  }

  const count = targetDb[COLLECTION_NAME].countDocuments({});
  if (count === 0) {
    print(`  Seeding ${seedData.length} documents...`);
    const result = targetDb[COLLECTION_NAME].insertMany(seedData);
    const inserted = Object.keys(result.insertedIds).length;
    print(`  Done — inserted ${inserted} documents.`);
  } else {
    print(`  Skipping seed — collection already contains ${count} document(s).`);
  }
});

print("\nInitialization complete.");
